spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/actors?characterEncoding=UTF-8
        username: root
        password: ssafy
    hikari:
        maximum-pool-size:180
        minimum-idle:10

#    jpa:
#        hibernate:
#            ddl-auto:create
#        properties:
#            hibernate:
#                format_sql:true
#                jdbc:
#                    time_zone:Asia/Seoul
#        show-sql:true
#
#    servlet:
#        multipart:
#            max-file-size:10MB
#            max-request-size:10MB
