

services:
  # 서비스 이름
  spring:
    container_name: spring
    hostname: spring
    # 실행되는 컨텍스트 및 도커파일 지정
    build:
      context: ../
      dockerfile: "./docker/dockerfile/spring.dockerfile"
    env_file: ".env"
    ports:
      - ${SPRING_PORT}:${SPRING_PORT}
    restart: "always"
    networks:
      - backend

  mysql:
    container_name: mysql
    hostname: mysql
    build:
      context: ../
      dockerfile: "./docker/dockerfile/mysql.dockerfile"
    networks:
      - backend
    env_file: ".env"
    expose:
      - ${MYSQL_PORT}

  flask:
    container_name: flask
    hostname: flask
    build:
      context: ../
      dockerfile: "./docker/dockerfile/flask.dockerfile"
    networks:
      - backend
    expose:
      - ${FLASK_PORT}

  elastic:
    build:
      context: ../
      dockerfile: "./docker/dockerfile/elastic-search.dockerfile"
    networks:
      - backend
    env_file: ".env"
    expose:
      - ${ELASTIC_PORT}

  redis:
    image: redis
    networks:
      - backend
    env_file: ".env"
    expose:
      - ${REDIS_PORT}
#
  rabbitmq:
    image: rabbitmq
    networks:
      - backend
    env_file: ".env"
    expose:
      - ${RABBIT_PORT}

# 브리지 네트워크는 도커가 제공하는 네트워크 드라이버 중 하나로, 가상
# 인터페이스를 통해 컨테이너들을 연결한다.
networks:
  backend:
    ipam:
      driver: default
      config:
        - subnet: "172.16.20.0/24"
          gateway: "172.16.20.1"