<<<<<<< HEAD
services:
  # 서비스 이름
#  spring:
#    container_name: spring
#    hostname: spring
#    # 실행되는 컨텍스트 및 도커파일 지정
#    build:
#      context: ../
#      dockerfile: "./docker/dockerfile/spring.dockerfile"
#    env_file: ".env"
#    restart: "always"
#    networks:
#      - backend

  mysql:
    container_name: mysql
    hostname: mysql
    build:
      context: ../
      dockerfile: "./docker/dockerfile/mysql.dockerfile"
    networks:
      - backend
    env_file: ".env"
    ports:
      - "3306:3306"
    restart: "always"

#  elastic:
#    build:
#      context: ../
#      dockerfile: "./docker/dockerfile/elastic-search.dockerfile"
#    networks:
#      - backend

  redis:
    image: redis
    networks:
      - backend
    ports:
      - "6379:6379"

#  rabbitMQ:
#    image: rabbitmq
#    networks:
#      backend:

# 브리지 네트워크는 도커가 제공하는 네트워크 드라이버 중 하나로, 가상
# 인터페이스를 통해 컨테이너들을 연결한다.
networks:
  backend:
    ipam:
      driver: default
      config:
        - subnet: "172.16.20.0/24"
=======
version: "2"

services:
  # 서비스 이름
  spring:
    container_name: spring
    hostname: spring
    # 실행되는 컨텍스트 및 도커파일 지정
    build:
      context: ../
      dockerfile: "./docker/dockerfile/spring.dockerfile"
    ports:
      - "8080:8080"
    restart: "always"
    networks:
      - backend

  mysql:
    container_name: mysql
    hostname: mysql
    build:
      context: ../
      dockerfile: "./docker/dockerfile/mysql.dockerfile"
    networks:
      - backend
    volumes:
      - /home/ubuntu/volume/mysql:/var/lib/mysql
    env_file: ".env"
    ports:
      - "3306:3306"

  flask:
    container_name: flask
    hostname: flask
    build:
      context: ../
      dockerfile: "./docker/dockerfile/flask.dockerfile"
    networks:
      - backend
    volumes:
      - /home/ubuntu/volume/flask:/usr/local/app/
    ports:
      - "5000:5000"

  elastic:
    build:
      context: ../
      dockerfile: "./docker/dockerfile/elastic-search.dockerfile"
    networks:
      - backend
    ports:
      - "9200:9200"

  redis:
    image: redis
    networks:
      - backend
    ports:
      - "6379:6379"
  #
  rabbitmq:
    image: rabbitmq
    networks:
      - backend
    volumes:
      - /home/ubuntu/volume/mq:/var/lib/rabbitmq
    ports:
      - "5672:5672"

  mongo:
    image: mongo
    networks:
      - backend
    volumes:
      - /home/ubuntu/volume/data:/data
    env_file: ".env"
    ports:
      - "27017:27017"

# 브리지 네트워크는 도커가 제공하는 네트워크 드라이버 중 하나로, 가상
# 인터페이스를 통해 컨테이너들을 연결한다.
networks:
  backend:
    ipam:
      driver: default
      config:
        - subnet: "172.16.20.0/24"
>>>>>>> a7e288c319f7400295bc05ac63f94c919f529845
          gateway: "172.16.20.1"