version: "2"

services:
  # 서비스 이름
  spring:
    container_name: spring
    hostname: spring
    # 실행되는 컨텍스트 및 도커파일 지정
    build:
      context: ../
      dockerfile: "./docker/dockerfile/spring.dockerfile"
    ports:
      - "8080:8080"
    restart: "always"
    networks:
      - backend

  mysql:
    container_name: mysql
    hostname: mysql
    build:
      context: ../
      dockerfile: "./docker/dockerfile/mysql.dockerfile"
    networks:
      - backend
    volumes:
      - /home/ubuntu/volume/mysql:/var/lib/mysql
    env_file: "docker.env"
    expose:
      - "3306"

  flask:
    container_name: flask
    hostname: flask
    build:
      context: ../
      dockerfile: "./docker/dockerfile/flask.dockerfile"
    networks:
      - backend
    volumes:
      - /home/ubuntu/volume/flask:/usr/local/app/
    env_file: "docker.env"
    expose:
      - "5000"

  elastic:
    build:
      context: ../
      dockerfile: "./docker/dockerfile/elastic-search.dockerfile"
    networks:
      - backend
    env_file: "docker.env"
    expose:
      - "9200"

  redis:
    image: redis
    networks:
      - backend
    env_file: "docker.env"
    expose:
      - "6379"
#
  rabbitmq:
    image: rabbitmq
    networks:
      - backend
    volumes:
      - /home/ubuntu/volume/mq:/var/lib/rabbitmq
    env_file: "docker.env"
    expose:
      - "5672"

  mongo:
    image: mongo
    networks:
      - backend
    volumes:
      - /home/ubuntu/volume/data:/data
    env_file: "docker.env"
    expose:
      - "27017"

# 브리지 네트워크는 도커가 제공하는 네트워크 드라이버 중 하나로, 가상
# 인터페이스를 통해 컨테이너들을 연결한다.
networks:
  backend:
    ipam:
      driver: default
      config:
        - subnet: "172.16.20.0/24"
          gateway: "172.16.20.1"